export const SampleSize = [
  {
    UKSize: 4,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 78,
    Waist: 60,
    Hips: 83.5,
  },
  {
    UKSize: 6,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 80.5,
    Waist: 62.5,
    Hips: 86,
  },
  {
    UKSize: 8,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 83,
    Waist: 65,
    Hips: 88.5,
  },
  {
    UKSize: 10,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 88,
    Waist: 70,
    Hips: 93.5,
  },
  {
    UKSize: 12,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 93,
    Waist: 75,
    Hips: 98.5,
  },
  {
    UKSize: 14,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 98,
    Waist: 80,
    Hips: 103.5,
  },
  {
    UKSize: 16,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 103,
    Waist: 85,
    Hips: 108.5,
  },
  {
    UKSize: 18,
    Version: "Straight",
    Brand: "ASOS",
    Bust: 110.5,
    Waist: 92.5,
    Hips: 116,
  },
  {
    UKSize: 4,
    Version: "Straight",
    Brand: "PLT",
    Bust: 78.5,
    Waist: 60.5,
    Hips: 86.5,
    LetterSize: "XS",
  },
  {
    UKSize: 6,
    Version: "Straight",
    Brand: "PLT",
    Bust: 81,
    Waist: 63,
    Hips: 89,
    LetterSize: "S",
  },
  {
    UKSize: 8,
    Version: "Straight",
    Brand: "PLT",
    Bust: 86,
    Waist: 68,
    Hips: 94,
    LetterSize: "S",
  },
  {
    UKSize: 10,
    Version: "Straight",
    Brand: "PLT",
    Bust: 91,
    Waist: 73,
    Hips: 99,
    LetterSize: "M",
  },
  {
    UKSize: 12,
    Version: "Straight",
    Brand: "PLT",
    Bust: 96,
    Waist: 78,
    Hips: 104,
    LetterSize: "M",
  },
  {
    UKSize: 14,
    Version: "Straight",
    Brand: "PLT",
    Bust: 101,
    Waist: 83,
    Hips: 109,
    LetterSize: "L",
  },
  {
    UKSize: 16,
    Version: "Straight",
    Brand: "PLT",
    Bust: 106,
    Waist: 88,
    Hips: 114,
    LetterSize: "L",
  },
  {
    UKSize: 18,
    Version: "Straight",
    Brand: "PLT",
    Bust: 112,
    Waist: 94,
    Hips: 120,
    LetterSize: "XL",
  },
  {
    UKSize: 4,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 80.6,
    Waist: 62.6,
    Hips: 87.6,
    LetterSize: "XS",
  },
  {
    UKSize: 6,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 82.6,
    Waist: 64.6,
    Hips: 89.6,
    LetterSize: "S",
  },
  {
    UKSize: 8,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 84.6,
    Waist: 66.6,
    Hips: 91.6,
    LetterSize: "S",
  },
  {
    UKSize: 10,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 87,
    Waist: 69,
    Hips: 94,
    LetterSize: "M",
  },
  {
    UKSize: 12,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 92,
    Waist: 74,
    Hips: 99,
    LetterSize: "M",
  },
  {
    UKSize: 14,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 98,
    Waist: 80,
    Hips: 105,
    LetterSize: "L",
  },
  {
    UKSize: 16,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 104,
    Waist: 86,
    Hips: 111,
    LetterSize: "L",
  },
  {
    UKSize: 18,
    Version: "Straight",
    Brand: "BOOHOO",
    Bust: 110,
    Waist: 92,
    Hips: 117,
    LetterSize: "XL",
  },
];
